<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Zomp.EFCore.BinaryFunctions.Npgsql\Zomp.EFCore.BinaryFunctions.Npgsql.csproj" />
    <ProjectReference Include="..\Zomp.EFCore.Testing\Zomp.EFCore.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Zomp.EFCore.BinaryFunctions.Npgsql"/>
    <Using Include="System.Buffers.Binary" />
    <Using Include="System.Runtime.CompilerServices" />
    <Using Include="System.Runtime.InteropServices" />
    <Using Include="Zomp.EFCore.BinaryFunctions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Zomp.EFCore.BinaryFunctions.Testing\**\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
