<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zomp.EFCore.WindowFunctions.Oracle\Zomp.EFCore.WindowFunctions.Oracle.csproj" />
    <ProjectReference Include="..\Zomp.EFCore.Testing\Zomp.EFCore.Testing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Zomp.EFCore.WindowFunctions.Testing\**\*.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
