#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

formatLevel=minimal
if [ -n "$1" ]; then
  formatLevel=$1
fi

EXIT_STATUS=0
dotnet.exe tool run dotnet-format --verify-no-changes Zomp.EFCore.Extensions.sln -v $formatLevel whitespace || EXIT_STATUS=$?
exit $EXIT_STATUS
