name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  dotnet_sdk_version: '6.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Start PostgreSQL on Windows
      run: |
        $pgService = Get-Service -Name postgresql*
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru

    - name: Set up PostgreSQL test user
      env:
        PGUSER: postgres
        PGPASSWORD: root
      run: |
        & $env:PGBIN\psql -c "CREATE USER npgsql_tests SUPERUSER PASSWORD 'npgsql_tests'"

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - run: yarn install

    - name: 'Run pre-commit hooks'
      shell: bash
      run: sh $(git config core.hooksPath)/pre-commit normal

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_sdk_version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
